[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cache_path  = "forge-cache"
solc-version = "0.8.27"
evm_version = "prague"
via_ir = true
optimizer = true
optimizer-runs = 2000

# Support for P2P library which uses 0.8.27
[profile.p2p]
solc-version = "0.8.27"
evm_version = "shanghai"
via_ir = true
optimizer = true
optimizer-runs = 2000

remappings = [
    # Safe contracts
    "@gnosis.pm/safe-contracts/=lib/safe-contracts/contracts/",
    # Zodiac (Modifier base, Module framework)
    "@zodiac/=lib/zodiac/contracts/",
    # Zodiac Roles (EVM package lives under packages/evm)
    "@roles/=lib/zodiac-modifier-roles/packages/evm/contracts/",
    # OpenZeppelin upgradeable contracts
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    # OpenZeppelin regular contracts (for non-upgradeable)
    "@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",

    "@safe-global/safe-contracts/=lib/safe-contracts/",
    "@gnosis.pm/zodiac/=lib/zodiac/",

    "p2p-lending-proxy/=lib/p2p-lending-proxy/",
    "permit2/=lib/permit2/",
    
    # ModuleKit dependencies
    "@ERC4337/=lib/modulekit/node_modules/@ERC4337/",
    "@prb/math/=lib/modulekit/node_modules/@prb/math/src/",
    "ExcessivelySafeCall/=lib/modulekit/node_modules/excessively-safe-call/src/",
    "account-abstraction-v0.6/=lib/modulekit/node_modules/@ERC4337/account-abstraction-v0.6/contracts/",
    "account-abstraction/=lib/modulekit/node_modules/@ERC4337/account-abstraction/contracts/",
    "ds-test/=lib/modulekit/node_modules/ds-test/src/",
    "erc4337-validation/=lib/modulekit/node_modules/@rhinestone/erc4337-validation/src/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "forge-gas-snapshot/=lib/permit2/lib/forge-gas-snapshot/src/",
    "forge-std/=lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts-upgradeable/lib/halmos-cheatcodes/src/",
    "modulekit/=lib/modulekit/src/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/",
    "safe-contracts/=lib/safe-contracts/contracts/",
    "solady/=lib/modulekit/node_modules/solady/src/",
    "solarray/=lib/modulekit/node_modules/solarray/src/",
    "solmate/=lib/permit2/lib/solmate/src/",
    "zodiac-modifier-roles/=lib/zodiac-modifier-roles/",
    "zodiac/=lib/zodiac/contracts/"
]

rpc_endpoints = { mainnet = "https://eth.drpc.org", sepolia = "https://rpc.ankr.com/eth_sepolia", base = "https://mainnet.base.org" }

# Skip problematic files that require modulekit dependencies not available in CI
skip = ["src/P2pEigenLayerModule.sol"]
